import NavBar from '@/components/navbar/NavBar'
import './globals.css'
import StoreData from './StoreData'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en"> 
      <body className="bg-background flex flex-col items-center text-t-gl relative">
        <nav className=' z-50 fixed w-screen flex flex-col items-center '>
          <NavBar/>
        </nav>
        <main className='mt-16'>
          <StoreData />
          {children}
        </main>
      </body>
    </html>
  )
}
